# db for local dev
version: "3.9"

services:
  postgresql:
    image: postgres:16.6-alpine # matches version used on aws environments
    container_name: pg-device-definitions
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dimo
      - POSTGRES_PASSWORD=dimo
      - POSTGRES_DB=vehicle_signal_decoding_api
    volumes:
      - postgresdb:/var/lib/postgresql/data:delegated

volumes:
  postgresdb:
    driver: local

networks:
  elastic:
    driver: bridge
