// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	DBCCodes                  string
	DBCFiles                  string
	PidConfigs                string
	PowerConfigs              string
	SerialToTemplateOverrides string
	TemplateTypes             string
	TemplateVehicles          string
	Templates                 string
	TestSignals               string
}{
	DBCCodes:                  "dbc_codes",
	DBCFiles:                  "dbc_files",
	PidConfigs:                "pid_configs",
	PowerConfigs:              "power_configs",
	SerialToTemplateOverrides: "serial_to_template_overrides",
	TemplateTypes:             "template_types",
	TemplateVehicles:          "template_vehicles",
	Templates:                 "templates",
	TestSignals:               "test_signals",
}
