// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	DBCCodes                  string
	DBCFiles                  string
	DeviceSettings            string
	DeviceTemplateStatus      string
	Jobs                      string
	PidConfigs                string
	SerialToTemplateOverrides string
	TemplateDeviceDefinitions string
	TemplateTypes             string
	TemplateVehicles          string
	Templates                 string
	TestSignals               string
}{
	DBCCodes:                  "dbc_codes",
	DBCFiles:                  "dbc_files",
	DeviceSettings:            "device_settings",
	DeviceTemplateStatus:      "device_template_status",
	Jobs:                      "jobs",
	PidConfigs:                "pid_configs",
	SerialToTemplateOverrides: "serial_to_template_overrides",
	TemplateDeviceDefinitions: "template_device_definitions",
	TemplateTypes:             "template_types",
	TemplateVehicles:          "template_vehicles",
	Templates:                 "templates",
	TestSignals:               "test_signals",
}
