// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// PowerConfig is an object representing the database table.
type PowerConfig struct {
	ID                                     int64     `boil:"id" json:"id" toml:"id" yaml:"id"`
	Version                                string    `boil:"version" json:"version" toml:"version" yaml:"version"`
	TemplateName                           string    `boil:"template_name" json:"template_name" toml:"template_name" yaml:"template_name"`
	BatteryCriticalLevelVoltage            string    `boil:"battery_critical_level_voltage" json:"battery_critical_level_voltage" toml:"battery_critical_level_voltage" yaml:"battery_critical_level_voltage"`
	SafetyCutOutVoltage                    string    `boil:"safety_cut_out_voltage" json:"safety_cut_out_voltage" toml:"safety_cut_out_voltage" yaml:"safety_cut_out_voltage"`
	SleepTimerEventDrivenInterval          string    `boil:"sleep_timer_event_driven_interval" json:"sleep_timer_event_driven_interval" toml:"sleep_timer_event_driven_interval" yaml:"sleep_timer_event_driven_interval"`
	SleepTimerEventDrivenPeriod            string    `boil:"sleep_timer_event_driven_period" json:"sleep_timer_event_driven_period" toml:"sleep_timer_event_driven_period" yaml:"sleep_timer_event_driven_period"`
	SleepTimerInactivityAfterSleepInterval string    `boil:"sleep_timer_inactivity_after_sleep_interval" json:"sleep_timer_inactivity_after_sleep_interval" toml:"sleep_timer_inactivity_after_sleep_interval" yaml:"sleep_timer_inactivity_after_sleep_interval"`
	SleepTimerInactivityFallbackInterval   string    `boil:"sleep_timer_inactivity_fallback_interval" json:"sleep_timer_inactivity_fallback_interval" toml:"sleep_timer_inactivity_fallback_interval" yaml:"sleep_timer_inactivity_fallback_interval"`
	WakeTriggerVoltageLevel                string    `boil:"wake_trigger_voltage_level" json:"wake_trigger_voltage_level" toml:"wake_trigger_voltage_level" yaml:"wake_trigger_voltage_level"`
	CreatedAt                              time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt                              time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *powerConfigR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L powerConfigL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var PowerConfigColumns = struct {
	ID                                     string
	Version                                string
	TemplateName                           string
	BatteryCriticalLevelVoltage            string
	SafetyCutOutVoltage                    string
	SleepTimerEventDrivenInterval          string
	SleepTimerEventDrivenPeriod            string
	SleepTimerInactivityAfterSleepInterval string
	SleepTimerInactivityFallbackInterval   string
	WakeTriggerVoltageLevel                string
	CreatedAt                              string
	UpdatedAt                              string
}{
	ID:                                     "id",
	Version:                                "version",
	TemplateName:                           "template_name",
	BatteryCriticalLevelVoltage:            "battery_critical_level_voltage",
	SafetyCutOutVoltage:                    "safety_cut_out_voltage",
	SleepTimerEventDrivenInterval:          "sleep_timer_event_driven_interval",
	SleepTimerEventDrivenPeriod:            "sleep_timer_event_driven_period",
	SleepTimerInactivityAfterSleepInterval: "sleep_timer_inactivity_after_sleep_interval",
	SleepTimerInactivityFallbackInterval:   "sleep_timer_inactivity_fallback_interval",
	WakeTriggerVoltageLevel:                "wake_trigger_voltage_level",
	CreatedAt:                              "created_at",
	UpdatedAt:                              "updated_at",
}

var PowerConfigTableColumns = struct {
	ID                                     string
	Version                                string
	TemplateName                           string
	BatteryCriticalLevelVoltage            string
	SafetyCutOutVoltage                    string
	SleepTimerEventDrivenInterval          string
	SleepTimerEventDrivenPeriod            string
	SleepTimerInactivityAfterSleepInterval string
	SleepTimerInactivityFallbackInterval   string
	WakeTriggerVoltageLevel                string
	CreatedAt                              string
	UpdatedAt                              string
}{
	ID:                                     "power_configs.id",
	Version:                                "power_configs.version",
	TemplateName:                           "power_configs.template_name",
	BatteryCriticalLevelVoltage:            "power_configs.battery_critical_level_voltage",
	SafetyCutOutVoltage:                    "power_configs.safety_cut_out_voltage",
	SleepTimerEventDrivenInterval:          "power_configs.sleep_timer_event_driven_interval",
	SleepTimerEventDrivenPeriod:            "power_configs.sleep_timer_event_driven_period",
	SleepTimerInactivityAfterSleepInterval: "power_configs.sleep_timer_inactivity_after_sleep_interval",
	SleepTimerInactivityFallbackInterval:   "power_configs.sleep_timer_inactivity_fallback_interval",
	WakeTriggerVoltageLevel:                "power_configs.wake_trigger_voltage_level",
	CreatedAt:                              "power_configs.created_at",
	UpdatedAt:                              "power_configs.updated_at",
}

// Generated where

var PowerConfigWhere = struct {
	ID                                     whereHelperint64
	Version                                whereHelperstring
	TemplateName                           whereHelperstring
	BatteryCriticalLevelVoltage            whereHelperstring
	SafetyCutOutVoltage                    whereHelperstring
	SleepTimerEventDrivenInterval          whereHelperstring
	SleepTimerEventDrivenPeriod            whereHelperstring
	SleepTimerInactivityAfterSleepInterval whereHelperstring
	SleepTimerInactivityFallbackInterval   whereHelperstring
	WakeTriggerVoltageLevel                whereHelperstring
	CreatedAt                              whereHelpertime_Time
	UpdatedAt                              whereHelpertime_Time
}{
	ID:                                     whereHelperint64{field: "\"vehicle_signal_decoding_api\".\"power_configs\".\"id\""},
	Version:                                whereHelperstring{field: "\"vehicle_signal_decoding_api\".\"power_configs\".\"version\""},
	TemplateName:                           whereHelperstring{field: "\"vehicle_signal_decoding_api\".\"power_configs\".\"template_name\""},
	BatteryCriticalLevelVoltage:            whereHelperstring{field: "\"vehicle_signal_decoding_api\".\"power_configs\".\"battery_critical_level_voltage\""},
	SafetyCutOutVoltage:                    whereHelperstring{field: "\"vehicle_signal_decoding_api\".\"power_configs\".\"safety_cut_out_voltage\""},
	SleepTimerEventDrivenInterval:          whereHelperstring{field: "\"vehicle_signal_decoding_api\".\"power_configs\".\"sleep_timer_event_driven_interval\""},
	SleepTimerEventDrivenPeriod:            whereHelperstring{field: "\"vehicle_signal_decoding_api\".\"power_configs\".\"sleep_timer_event_driven_period\""},
	SleepTimerInactivityAfterSleepInterval: whereHelperstring{field: "\"vehicle_signal_decoding_api\".\"power_configs\".\"sleep_timer_inactivity_after_sleep_interval\""},
	SleepTimerInactivityFallbackInterval:   whereHelperstring{field: "\"vehicle_signal_decoding_api\".\"power_configs\".\"sleep_timer_inactivity_fallback_interval\""},
	WakeTriggerVoltageLevel:                whereHelperstring{field: "\"vehicle_signal_decoding_api\".\"power_configs\".\"wake_trigger_voltage_level\""},
	CreatedAt:                              whereHelpertime_Time{field: "\"vehicle_signal_decoding_api\".\"power_configs\".\"created_at\""},
	UpdatedAt:                              whereHelpertime_Time{field: "\"vehicle_signal_decoding_api\".\"power_configs\".\"updated_at\""},
}

// PowerConfigRels is where relationship names are stored.
var PowerConfigRels = struct {
	TemplateNameTemplate string
}{
	TemplateNameTemplate: "TemplateNameTemplate",
}

// powerConfigR is where relationships are stored.
type powerConfigR struct {
	TemplateNameTemplate *Template `boil:"TemplateNameTemplate" json:"TemplateNameTemplate" toml:"TemplateNameTemplate" yaml:"TemplateNameTemplate"`
}

// NewStruct creates a new relationship struct
func (*powerConfigR) NewStruct() *powerConfigR {
	return &powerConfigR{}
}

func (r *powerConfigR) GetTemplateNameTemplate() *Template {
	if r == nil {
		return nil
	}
	return r.TemplateNameTemplate
}

// powerConfigL is where Load methods for each relationship are stored.
type powerConfigL struct{}

var (
	powerConfigAllColumns            = []string{"id", "version", "template_name", "battery_critical_level_voltage", "safety_cut_out_voltage", "sleep_timer_event_driven_interval", "sleep_timer_event_driven_period", "sleep_timer_inactivity_after_sleep_interval", "sleep_timer_inactivity_fallback_interval", "wake_trigger_voltage_level", "created_at", "updated_at"}
	powerConfigColumnsWithoutDefault = []string{"version", "template_name", "battery_critical_level_voltage", "safety_cut_out_voltage", "sleep_timer_event_driven_interval", "sleep_timer_event_driven_period", "sleep_timer_inactivity_after_sleep_interval", "sleep_timer_inactivity_fallback_interval", "wake_trigger_voltage_level"}
	powerConfigColumnsWithDefault    = []string{"id", "created_at", "updated_at"}
	powerConfigPrimaryKeyColumns     = []string{"template_name"}
	powerConfigGeneratedColumns      = []string{}
)

type (
	// PowerConfigSlice is an alias for a slice of pointers to PowerConfig.
	// This should almost always be used instead of []PowerConfig.
	PowerConfigSlice []*PowerConfig
	// PowerConfigHook is the signature for custom PowerConfig hook methods
	PowerConfigHook func(context.Context, boil.ContextExecutor, *PowerConfig) error

	powerConfigQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	powerConfigType                 = reflect.TypeOf(&PowerConfig{})
	powerConfigMapping              = queries.MakeStructMapping(powerConfigType)
	powerConfigPrimaryKeyMapping, _ = queries.BindMapping(powerConfigType, powerConfigMapping, powerConfigPrimaryKeyColumns)
	powerConfigInsertCacheMut       sync.RWMutex
	powerConfigInsertCache          = make(map[string]insertCache)
	powerConfigUpdateCacheMut       sync.RWMutex
	powerConfigUpdateCache          = make(map[string]updateCache)
	powerConfigUpsertCacheMut       sync.RWMutex
	powerConfigUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var powerConfigAfterSelectHooks []PowerConfigHook

var powerConfigBeforeInsertHooks []PowerConfigHook
var powerConfigAfterInsertHooks []PowerConfigHook

var powerConfigBeforeUpdateHooks []PowerConfigHook
var powerConfigAfterUpdateHooks []PowerConfigHook

var powerConfigBeforeDeleteHooks []PowerConfigHook
var powerConfigAfterDeleteHooks []PowerConfigHook

var powerConfigBeforeUpsertHooks []PowerConfigHook
var powerConfigAfterUpsertHooks []PowerConfigHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *PowerConfig) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range powerConfigAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *PowerConfig) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range powerConfigBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *PowerConfig) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range powerConfigAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *PowerConfig) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range powerConfigBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *PowerConfig) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range powerConfigAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *PowerConfig) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range powerConfigBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *PowerConfig) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range powerConfigAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *PowerConfig) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range powerConfigBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *PowerConfig) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range powerConfigAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddPowerConfigHook registers your hook function for all future operations.
func AddPowerConfigHook(hookPoint boil.HookPoint, powerConfigHook PowerConfigHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		powerConfigAfterSelectHooks = append(powerConfigAfterSelectHooks, powerConfigHook)
	case boil.BeforeInsertHook:
		powerConfigBeforeInsertHooks = append(powerConfigBeforeInsertHooks, powerConfigHook)
	case boil.AfterInsertHook:
		powerConfigAfterInsertHooks = append(powerConfigAfterInsertHooks, powerConfigHook)
	case boil.BeforeUpdateHook:
		powerConfigBeforeUpdateHooks = append(powerConfigBeforeUpdateHooks, powerConfigHook)
	case boil.AfterUpdateHook:
		powerConfigAfterUpdateHooks = append(powerConfigAfterUpdateHooks, powerConfigHook)
	case boil.BeforeDeleteHook:
		powerConfigBeforeDeleteHooks = append(powerConfigBeforeDeleteHooks, powerConfigHook)
	case boil.AfterDeleteHook:
		powerConfigAfterDeleteHooks = append(powerConfigAfterDeleteHooks, powerConfigHook)
	case boil.BeforeUpsertHook:
		powerConfigBeforeUpsertHooks = append(powerConfigBeforeUpsertHooks, powerConfigHook)
	case boil.AfterUpsertHook:
		powerConfigAfterUpsertHooks = append(powerConfigAfterUpsertHooks, powerConfigHook)
	}
}

// One returns a single powerConfig record from the query.
func (q powerConfigQuery) One(ctx context.Context, exec boil.ContextExecutor) (*PowerConfig, error) {
	o := &PowerConfig{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for power_configs")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all PowerConfig records from the query.
func (q powerConfigQuery) All(ctx context.Context, exec boil.ContextExecutor) (PowerConfigSlice, error) {
	var o []*PowerConfig

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to PowerConfig slice")
	}

	if len(powerConfigAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all PowerConfig records in the query.
func (q powerConfigQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count power_configs rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q powerConfigQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if power_configs exists")
	}

	return count > 0, nil
}

// TemplateNameTemplate pointed to by the foreign key.
func (o *PowerConfig) TemplateNameTemplate(mods ...qm.QueryMod) templateQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"template_name\" = ?", o.TemplateName),
	}

	queryMods = append(queryMods, mods...)

	return Templates(queryMods...)
}

// LoadTemplateNameTemplate allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (powerConfigL) LoadTemplateNameTemplate(ctx context.Context, e boil.ContextExecutor, singular bool, maybePowerConfig interface{}, mods queries.Applicator) error {
	var slice []*PowerConfig
	var object *PowerConfig

	if singular {
		var ok bool
		object, ok = maybePowerConfig.(*PowerConfig)
		if !ok {
			object = new(PowerConfig)
			ok = queries.SetFromEmbeddedStruct(&object, &maybePowerConfig)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybePowerConfig))
			}
		}
	} else {
		s, ok := maybePowerConfig.(*[]*PowerConfig)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybePowerConfig)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybePowerConfig))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &powerConfigR{}
		}
		args = append(args, object.TemplateName)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &powerConfigR{}
			}

			for _, a := range args {
				if a == obj.TemplateName {
					continue Outer
				}
			}

			args = append(args, obj.TemplateName)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`vehicle_signal_decoding_api.templates`),
		qm.WhereIn(`vehicle_signal_decoding_api.templates.template_name in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Template")
	}

	var resultSlice []*Template
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Template")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for templates")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for templates")
	}

	if len(templateAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.TemplateNameTemplate = foreign
		if foreign.R == nil {
			foreign.R = &templateR{}
		}
		foreign.R.TemplateNamePowerConfig = object
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.TemplateName == foreign.TemplateName {
				local.R.TemplateNameTemplate = foreign
				if foreign.R == nil {
					foreign.R = &templateR{}
				}
				foreign.R.TemplateNamePowerConfig = local
				break
			}
		}
	}

	return nil
}

// SetTemplateNameTemplate of the powerConfig to the related item.
// Sets o.R.TemplateNameTemplate to related.
// Adds o to related.R.TemplateNamePowerConfig.
func (o *PowerConfig) SetTemplateNameTemplate(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Template) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"vehicle_signal_decoding_api\".\"power_configs\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"template_name"}),
		strmangle.WhereClause("\"", "\"", 2, powerConfigPrimaryKeyColumns),
	)
	values := []interface{}{related.TemplateName, o.TemplateName}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.TemplateName = related.TemplateName
	if o.R == nil {
		o.R = &powerConfigR{
			TemplateNameTemplate: related,
		}
	} else {
		o.R.TemplateNameTemplate = related
	}

	if related.R == nil {
		related.R = &templateR{
			TemplateNamePowerConfig: o,
		}
	} else {
		related.R.TemplateNamePowerConfig = o
	}

	return nil
}

// PowerConfigs retrieves all the records using an executor.
func PowerConfigs(mods ...qm.QueryMod) powerConfigQuery {
	mods = append(mods, qm.From("\"vehicle_signal_decoding_api\".\"power_configs\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"vehicle_signal_decoding_api\".\"power_configs\".*"})
	}

	return powerConfigQuery{q}
}

// FindPowerConfig retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindPowerConfig(ctx context.Context, exec boil.ContextExecutor, templateName string, selectCols ...string) (*PowerConfig, error) {
	powerConfigObj := &PowerConfig{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"vehicle_signal_decoding_api\".\"power_configs\" where \"template_name\"=$1", sel,
	)

	q := queries.Raw(query, templateName)

	err := q.Bind(ctx, exec, powerConfigObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from power_configs")
	}

	if err = powerConfigObj.doAfterSelectHooks(ctx, exec); err != nil {
		return powerConfigObj, err
	}

	return powerConfigObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *PowerConfig) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no power_configs provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(powerConfigColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	powerConfigInsertCacheMut.RLock()
	cache, cached := powerConfigInsertCache[key]
	powerConfigInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			powerConfigAllColumns,
			powerConfigColumnsWithDefault,
			powerConfigColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(powerConfigType, powerConfigMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(powerConfigType, powerConfigMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"vehicle_signal_decoding_api\".\"power_configs\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"vehicle_signal_decoding_api\".\"power_configs\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into power_configs")
	}

	if !cached {
		powerConfigInsertCacheMut.Lock()
		powerConfigInsertCache[key] = cache
		powerConfigInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the PowerConfig.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *PowerConfig) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	powerConfigUpdateCacheMut.RLock()
	cache, cached := powerConfigUpdateCache[key]
	powerConfigUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			powerConfigAllColumns,
			powerConfigPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update power_configs, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"vehicle_signal_decoding_api\".\"power_configs\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, powerConfigPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(powerConfigType, powerConfigMapping, append(wl, powerConfigPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update power_configs row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for power_configs")
	}

	if !cached {
		powerConfigUpdateCacheMut.Lock()
		powerConfigUpdateCache[key] = cache
		powerConfigUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q powerConfigQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for power_configs")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for power_configs")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o PowerConfigSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), powerConfigPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"vehicle_signal_decoding_api\".\"power_configs\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, powerConfigPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in powerConfig slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all powerConfig")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *PowerConfig) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no power_configs provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(powerConfigColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	powerConfigUpsertCacheMut.RLock()
	cache, cached := powerConfigUpsertCache[key]
	powerConfigUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			powerConfigAllColumns,
			powerConfigColumnsWithDefault,
			powerConfigColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			powerConfigAllColumns,
			powerConfigPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert power_configs, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(powerConfigPrimaryKeyColumns))
			copy(conflict, powerConfigPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"vehicle_signal_decoding_api\".\"power_configs\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(powerConfigType, powerConfigMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(powerConfigType, powerConfigMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert power_configs")
	}

	if !cached {
		powerConfigUpsertCacheMut.Lock()
		powerConfigUpsertCache[key] = cache
		powerConfigUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single PowerConfig record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *PowerConfig) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no PowerConfig provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), powerConfigPrimaryKeyMapping)
	sql := "DELETE FROM \"vehicle_signal_decoding_api\".\"power_configs\" WHERE \"template_name\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from power_configs")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for power_configs")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q powerConfigQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no powerConfigQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from power_configs")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for power_configs")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o PowerConfigSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(powerConfigBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), powerConfigPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"vehicle_signal_decoding_api\".\"power_configs\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, powerConfigPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from powerConfig slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for power_configs")
	}

	if len(powerConfigAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *PowerConfig) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindPowerConfig(ctx, exec, o.TemplateName)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *PowerConfigSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := PowerConfigSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), powerConfigPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"vehicle_signal_decoding_api\".\"power_configs\".* FROM \"vehicle_signal_decoding_api\".\"power_configs\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, powerConfigPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in PowerConfigSlice")
	}

	*o = slice

	return nil
}

// PowerConfigExists checks if the PowerConfig row exists.
func PowerConfigExists(ctx context.Context, exec boil.ContextExecutor, templateName string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"vehicle_signal_decoding_api\".\"power_configs\" where \"template_name\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, templateName)
	}
	row := exec.QueryRowContext(ctx, sql, templateName)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if power_configs exists")
	}

	return exists, nil
}

// Exists checks if the PowerConfig row exists.
func (o *PowerConfig) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return PowerConfigExists(ctx, exec, o.TemplateName)
}
