apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "vehicle-signal-decoding.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
spec:
  data:
    - remoteRef:
        key: {{ .Release.Namespace }}/decoding/db/host
      secretKey: DB_HOST
    - remoteRef:
        key: {{ .Release.Namespace }}/decoding/db/user
      secretKey: DB_USER
    - remoteRef:
        key: {{ .Release.Namespace }}/decoding/db/pass
      secretKey: DB_PASSWORD
    - remoteRef:
        key: {{ .Release.Namespace }}/candumps/s3/keyid
      secretKey: CANDUMPS_AWS_ACCESS_KEY_ID
    - remoteRef:
        key: {{ .Release.Namespace }}/candumps/s3/accesskey
      secretKey: CANDUMPS_AWS_SECRET_ACCESS_KEY
    - remoteRef:
        key: {{ .Release.Namespace }}/candumps/s3/endpoint
      secretKey: CANDUMPS_AWS_ENDPOINT
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager-secret-store
  target:
    name: {{ include "vehicle-signal-decoding.fullname" . }}-secret
    template:
      metadata: { }