apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: {{ include "vehicle-signal-decoding.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
spec:
  backendType: secretsManager
  data:
    - key: {{ .Release.Namespace }}/definitions/db/host
      name: DB_HOST
    - key: {{ .Release.Namespace }}/definitions/db/user
      name: DB_USER
    - key: {{ .Release.Namespace }}/definitions/db/pass
      name: DB_PASSWORD
    - key: {{ .Release.Namespace }}/devices/redis/host
      name: REDIS_HOST
    - key: {{ .Release.Namespace }}/devices/redis/url
      name: REDIS_URL
    - key: {{ .Release.Namespace }}/devices/redis/password
      name: REDIS_PASSWORD
    - key: {{ .Release.Namespace }}/devices/elastic/appsearch/host
      name: ELASTIC_SEARCH_APP_SEARCH_HOST
    - key: {{ .Release.Namespace }}/devices/elastic/appsearch/token
      name: ELASTIC_SEARCH_APP_SEARCH_TOKEN
    - key: {{ .Release.Namespace }}/definitions/elastic/device_status/host
      name: ELASTIC_SEARCH_DEVICE_STATUS_HOST
    - key: {{ .Release.Namespace }}/definitions/elastic/device_status/token
      name: ELASTIC_SEARCH_DEVICE_STATUS_TOKEN
    - key: {{ .Release.Namespace }}/devices/drivly/apikey
      name: DRIVLY_API_KEY
    - key: {{ .Release.Namespace }}/definitions/fuelapi/apikey
      name: FUEL_API_KEY
