// Code generated by MockGen. DO NOT EDIT.
// Source: identity_api.go
//
// Generated by this command:
//
//	mockgen -source identity_api.go -destination mocks/identity_api_mock.go
//

// Package mock_gateways is a generated GoMock package.
package mock_gateways

import (
	reflect "reflect"

	gateways "github.com/DIMO-Network/vehicle-signal-decoding/internal/gateways"
	common "github.com/ethereum/go-ethereum/common"
	gomock "go.uber.org/mock/gomock"
)

// MockIdentityAPI is a mock of IdentityAPI interface.
type MockIdentityAPI struct {
	ctrl     *gomock.Controller
	recorder *MockIdentityAPIMockRecorder
}

// MockIdentityAPIMockRecorder is the mock recorder for MockIdentityAPI.
type MockIdentityAPIMockRecorder struct {
	mock *MockIdentityAPI
}

// NewMockIdentityAPI creates a new mock instance.
func NewMockIdentityAPI(ctrl *gomock.Controller) *MockIdentityAPI {
	mock := &MockIdentityAPI{ctrl: ctrl}
	mock.recorder = &MockIdentityAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdentityAPI) EXPECT() *MockIdentityAPIMockRecorder {
	return m.recorder
}

// GetDefinitionByID mocks base method.
func (m *MockIdentityAPI) GetDefinitionByID(definitionID string) (*gateways.DeviceDefinition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDefinitionByID", definitionID)
	ret0, _ := ret[0].(*gateways.DeviceDefinition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDefinitionByID indicates an expected call of GetDefinitionByID.
func (mr *MockIdentityAPIMockRecorder) GetDefinitionByID(definitionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDefinitionByID", reflect.TypeOf((*MockIdentityAPI)(nil).GetDefinitionByID), definitionID)
}

// GetVehicleByDeviceAddr mocks base method.
func (m *MockIdentityAPI) GetVehicleByDeviceAddr(ethAddress common.Address) (*gateways.VehicleInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVehicleByDeviceAddr", ethAddress)
	ret0, _ := ret[0].(*gateways.VehicleInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVehicleByDeviceAddr indicates an expected call of GetVehicleByDeviceAddr.
func (mr *MockIdentityAPIMockRecorder) GetVehicleByDeviceAddr(ethAddress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVehicleByDeviceAddr", reflect.TypeOf((*MockIdentityAPI)(nil).GetVehicleByDeviceAddr), ethAddress)
}
