basePath: /v1
definitions:
  device.ConfigResponse:
    properties:
      dbcUrl:
        description: DbcURL including the version for the dbc file, usually same as
          pidurl template version
        type: string
      deviceSettingUrl:
        description: DeviceSettingURL including the version for the settings
        type: string
      pidUrl:
        description: PidURL including the version for the template
        type: string
    type: object
  github_com_DIMO-Network_vehicle-signal-decoding_pkg_grpc.DeviceSetting:
    properties:
      battery_critical_level_voltage:
        type: number
      location_frequency_secs:
        type: number
      min_voltage_obd_loggers:
        type: number
      safety_cut_out_voltage:
        type: number
      sleep_timer_event_driven_interval_secs:
        type: number
      sleep_timer_event_driven_period_secs:
        type: number
      sleep_timer_inactivity_after_sleep_secs:
        type: number
      sleep_timer_inactivity_fallback_interval_secs:
        type: number
      template_name:
        type: string
      wake_trigger_voltage_level:
        type: number
    type: object
  github_com_DIMO-Network_vehicle-signal-decoding_pkg_grpc.PIDConfig:
    properties:
      can_flow_control_clear:
        type: boolean
      can_flow_control_id_pair:
        description: can be used to specify a custom response header. format is hex,hex
          - second hex is the resp header
        type: string
      formula:
        type: string
      header:
        type: integer
      interval_seconds:
        type: integer
      mode:
        type: integer
      name:
        type: string
      pid:
        type: integer
      protocol:
        type: string
    type: object
  github_com_DIMO-Network_vehicle-signal-decoding_pkg_grpc.PIDRequests:
    properties:
      requests:
        items:
          $ref: '#/definitions/github_com_DIMO-Network_vehicle-signal-decoding_pkg_grpc.PIDConfig'
        type: array
      template_name:
        type: string
      version:
        type: string
    type: object
  internal_controllers.DeviceTemplateStatusPatch:
    properties:
      dbcUrl:
        description: DbcURL including the version for the dbc file, usually same as
          pidurl template version
        type: string
      deviceSettingUrl:
        description: DeviceSettingURL including the version for the settings
        type: string
      firmwareVersionApplied:
        description: FirmwareVersionApplied version of firmware that was confirmed
          installed on device
        type: string
      pidUrl:
        description: PidURL including the version for the template
        type: string
      pidsUrl:
        description: |-
          PidsURL exists for backwards compatibility
          Deprecated
        type: string
      settingsUrl:
        description: |-
          SettingsUrl exists for backwards compatibiltiy
          Deprecated
        type: string
    type: object
  internal_controllers.DeviceTemplateStatusResponse:
    properties:
      firmwareVersion:
        type: string
      isFirmwareUpToDate:
        type: boolean
      isTemplateUpToDate:
        description: IsTemplateUpToDate based on information we have, based on what
          was set last by mobile app
        type: boolean
      template:
        allOf:
        - $ref: '#/definitions/device.ConfigResponse'
        description: Template contains the current urls server has for this device
    type: object
  internal_controllers.JobResponse:
    properties:
      command:
        type: string
      id:
        type: string
      status:
        type: string
    type: object
info:
  contact: {}
  title: DIMO Vehicle-Signal-Decoding
  version: "1.0"
paths:
  /device-config/dbc/{templateName}:
    get:
      description: Fetches the DBC file from the dbc_files table given a template
        name. Will get all the parent dbc files as well and meld them together
      parameters:
      - description: template name
        in: path
        name: templateName
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: Successfully retrieved DBC file
          schema:
            type: string
        "404":
          description: No DBC file found for the given template name.
      tags:
      - device-config
  /device-config/eth-addr/{ethAddr}/hw/status:
    patch:
      description: Set what template and/or firmware was applied. None of the properties
        are required. Will not be set if not passed in. Endpoint is meant only for
        hardware devices self-reporting their template update.
      parameters:
      - description: Ethereum Address
        in: path
        name: ethAddr
        required: true
        type: string
      - description: set any properties that were updated on the device
        in: body
        name: config
        required: true
        schema:
          $ref: '#/definitions/internal_controllers.DeviceTemplateStatusPatch'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully updated
        "500":
          description: unable to parse request or storage failure
      security:
      - SignatureAuth: []
      tags:
      - device-config
  /device-config/eth-addr/{ethAddr}/jobs:
    get:
      description: Retrieve the jobs based on device's Ethereum Address.
      parameters:
      - description: Ethereum Address
        in: path
        name: ethAddr
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved jobs
          schema:
            $ref: '#/definitions/internal_controllers.JobResponse'
        "400":
          description: incorrect eth addr format
      tags:
      - vehicle-signal-decoding
  /device-config/eth-addr/{ethAddr}/jobs/{jobId}/{status}:
    patch:
      description: Path job status based on device's Ethereum Address.
      parameters:
      - description: Ethereum Address
        in: path
        name: ethAddr
        type: string
      - description: Job ID
        in: path
        name: jobId
        type: string
      - description: Status to set
        in: path
        name: status
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: incorrect eth addr format
        "404":
          description: Not Found - No job found with id
      tags:
      - vehicle-signal-decoding
  /device-config/eth-addr/{ethAddr}/jobs/pending:
    get:
      description: Retrieve the jobs based on device's Ethereum Address.
      parameters:
      - description: Ethereum Address
        in: path
        name: ethAddr
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved jobs
          schema:
            $ref: '#/definitions/internal_controllers.JobResponse'
        "400":
          description: incorrect eth addr format
      tags:
      - vehicle-signal-decoding
  /device-config/eth-addr/{ethAddr}/status:
    get:
      description: Helps client determine if template (pids, dbc, settings) are up
        to date or not for the device with the given eth addr.
      parameters:
      - description: Ethereum Address
        in: path
        name: ethAddr
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved configuration URLs
          schema:
            $ref: '#/definitions/internal_controllers.DeviceTemplateStatusResponse'
        "400":
          description: incorrect eth addr format
        "404":
          description: Not Found - we haven't seen this device yet, assume template
            not up to date
      tags:
      - device-config
    patch:
      description: Set what template and/or firmware was applied. None of the properties
        are required. Will not be set if not passed in.
      parameters:
      - description: Ethereum Address
        in: path
        name: ethAddr
        required: true
        type: string
      - description: set any properties that were updated on the device
        in: body
        name: config
        required: true
        schema:
          $ref: '#/definitions/internal_controllers.DeviceTemplateStatusPatch'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully updated
        "500":
          description: unable to parse request or storage failure
      security:
      - BearerAuth: []
      tags:
      - device-config
  /device-config/eth-addr/{ethAddr}/urls:
    get:
      description: Retrieve the URLs for PID, DeviceSettings, and DBC configuration
        based on device's Ethereum Address. These could be empty if not configs available
      parameters:
      - description: Ethereum Address
        in: path
        name: ethAddr
        required: true
        type: string
      - description: CAN Protocol, '6' or '7'
        in: query
        name: protocol
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved configuration URLs
          schema:
            $ref: '#/definitions/device.ConfigResponse'
        "400":
          description: incorrect eth addr format
        "404":
          description: Not Found - No templates available for the given parameters
      tags:
      - device-config
  /device-config/pids/{templateName}:
    get:
      description: Retrieves a list of PID configurations from the database given
        a template name
      parameters:
      - description: template name
        in: path
        name: templateName
        required: true
        type: string
      produces:
      - application/json
      - application/x-protobuf
      responses:
        "200":
          description: Successfully retrieved PID Configurations
          schema:
            $ref: '#/definitions/github_com_DIMO-Network_vehicle-signal-decoding_pkg_grpc.PIDRequests'
        "404":
          description: No PID Config data found for the given template name.
      tags:
      - device-config
  /device-config/settings/{name}:
    get:
      description: |-
        Fetches the device settings configurations from device_settings table given a name. Note that device settings mostly only vary by powertrain and
        may or may not be attached to a specific template. To return protobuf: "application/x-protobuf"
        Note that the templateName returned here is actually the device setting name
      parameters:
      - description: name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      - application/x-protobuf
      responses:
        "200":
          description: Successfully retrieved Device Settings
          schema:
            $ref: '#/definitions/github_com_DIMO-Network_vehicle-signal-decoding_pkg_grpc.DeviceSetting'
        "404":
          description: No Device Settings data found for the given name.
      tags:
      - device-config
  /device-config/vin/{vin}/urls:
    get:
      description: Retrieve the URLs for PID, DeviceSettings, and DBC configuration
        based on a given VIN. These could be empty if not configs available
      parameters:
      - description: vehicle identification number (VIN)
        in: path
        name: vin
        required: true
        type: string
      - description: CAN Protocol, '6' or '7', 8,9,66,77,88,99
        in: query
        name: protocol
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved configuration URLs
          schema:
            $ref: '#/definitions/device.ConfigResponse'
        "404":
          description: Not Found - No templates available for the given parameters
      tags:
      - device-config
securityDefinitions:
  BearerAuth:
    description: 'Flow to get your device config: start by Getting the URL''s to your
      device''s configuration: `/device-config/eth-addr/:ethAddr/urls` or by vin,
      check readme for details.'
    in: header
    name: Authorization
    type: apiKey
  SignatureAuth:
    in: header
    name: Signature
    type: apiKey
swagger: "2.0"
