basePath: /v1
definitions:
  github_com_DIMO-Network_vehicle-signal-decoding_pkg_grpc.PIDConfig:
    properties:
      formula:
        type: string
      header:
        type: integer
      interval_seconds:
        type: integer
      mode:
        type: integer
      name:
        type: string
      pid:
        type: integer
      protocol:
        type: string
      version:
        type: string
    type: object
  github_com_DIMO-Network_vehicle-signal-decoding_pkg_grpc.PIDRequests:
    properties:
      requests:
        items:
          $ref: '#/definitions/github_com_DIMO-Network_vehicle-signal-decoding_pkg_grpc.PIDConfig'
        type: array
      template_name:
        type: string
      version:
        type: string
    type: object
  internal_controllers.DeviceSetting:
    properties:
      battery_critical_level_voltage:
        type: string
      created_at:
        type: string
      id:
        type: integer
      safety_cut_out_voltage:
        type: string
      sleep_timer_event_driven_interval:
        type: string
      sleep_timer_event_driven_period:
        type: string
      sleep_timer_inactivity_after_sleep_interval:
        type: string
      sleep_timer_inactivity_fallback_interval:
        type: string
      template_name:
        type: string
      updated_at:
        type: string
      wake_trigger_voltage_level:
        type: string
    type: object
info:
  contact: {}
  title: DIMO Vehicle-Signal-Decoding
  version: "1.0"
paths:
  /device-config/{templateName}/dbc-file:
    get:
      description: Fetches the DBC file from the dbc_files table given a template
        name
      parameters:
      - description: template name
        in: path
        name: templateName
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: Successfully retrieved DBC file
          schema:
            type: string
        "404":
          description: No DBC file found for the given template name.
      tags:
      - vehicle-signal-decoding
  /device-config/{templateName}/deviceSettings:
    get:
      description: Fetches the device settings configurations from device_settings
        table given a template name
      parameters:
      - description: template name
        in: path
        name: templateName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved Device Settings
          schema:
            $ref: '#/definitions/internal_controllers.DeviceSetting'
        "404":
          description: No Device Settings data found for the given template name.
      tags:
      - vehicle-signal-decoding
  /device-config/{templateName}/pids:
    get:
      description: Retrieves a list of PID configurations from the database given
        a template name
      parameters:
      - description: template name
        in: path
        name: templateName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved PID Configurations
          schema:
            $ref: '#/definitions/github_com_DIMO-Network_vehicle-signal-decoding_pkg_grpc.PIDRequests'
        "404":
          description: No PID Config data found for the given template name.
      tags:
      - vehicle-signal-decoding
  /device-config/{vin}/urls:
    get:
      description: Retrieve the URLs for PID, DeviceSettings, and DBC configuration
        based on a given VIN
      parameters:
      - description: vehicle identification number (VIN)
        in: path
        name: vin
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - vehicle-signal-decoding
swagger: "2.0"
