basePath: /v1
definitions:
  github_com_DIMO-Network_vehicle-signal-decoding_pkg_grpc.DeviceSetting:
    properties:
      battery_critical_level_voltage:
        type: number
      safety_cut_out_voltage:
        type: number
      sleep_timer_event_driven_interval_secs:
        type: number
      sleep_timer_event_driven_period_secs:
        type: number
      sleep_timer_inactivity_after_sleep_secs:
        type: number
      sleep_timer_inactivity_fallback_interval_secs:
        type: number
      template_name:
        type: string
      wake_trigger_voltage_level:
        type: number
    type: object
  github_com_DIMO-Network_vehicle-signal-decoding_pkg_grpc.PIDConfig:
    properties:
      formula:
        type: string
      header:
        type: integer
      interval_seconds:
        type: integer
      mode:
        type: integer
      name:
        type: string
      pid:
        type: integer
      protocol:
        type: string
    type: object
  github_com_DIMO-Network_vehicle-signal-decoding_pkg_grpc.PIDRequests:
    properties:
      requests:
        items:
          $ref: '#/definitions/github_com_DIMO-Network_vehicle-signal-decoding_pkg_grpc.PIDConfig'
        type: array
      template_name:
        type: string
      version:
        type: string
    type: object
  internal_controllers.DeviceConfigResponse:
    properties:
      dbcURL:
        type: string
      deviceSettingUrl:
        type: string
      pidUrl:
        type: string
      version:
        type: string
    type: object
  internal_controllers.JobResponse:
    properties:
      command:
        type: string
      id:
        type: string
      status:
        type: string
    type: object
info:
  contact: {}
  title: DIMO Vehicle-Signal-Decoding
  version: "1.0"
paths:
  /device-config/{templateName}/dbc:
    get:
      description: Fetches the DBC file from the dbc_files table given a template
        name
      parameters:
      - description: template name
        in: path
        name: templateName
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: Successfully retrieved DBC file
          schema:
            type: string
        "404":
          description: No DBC file found for the given template name.
      tags:
      - vehicle-signal-decoding
  /device-config/{templateName}/pids:
    get:
      description: Retrieves a list of PID configurations from the database given
        a template name
      parameters:
      - description: template name
        in: path
        name: templateName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved PID Configurations
          schema:
            $ref: '#/definitions/github_com_DIMO-Network_vehicle-signal-decoding_pkg_grpc.PIDRequests'
        "404":
          description: No PID Config data found for the given template name.
      tags:
      - vehicle-signal-decoding
  /device-config/eth-addr/{ethAddr}/jobs:
    get:
      description: Retrieve the jobs based on device's Ethereum Address.
      parameters:
      - description: Ethereum Address
        in: path
        name: ethAddr
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved jobs
          schema:
            $ref: '#/definitions/internal_controllers.JobResponse'
        "400":
          description: incorrect eth addr format
      tags:
      - vehicle-signal-decoding
  /device-config/eth-addr/{ethAddr}/jobs/{jobId}/{status}:
    patch:
      description: Path job status based on device's Ethereum Address.
      parameters:
      - description: Ethereum Address
        in: path
        name: ethAddr
        type: string
      - description: Job ID
        in: path
        name: jobId
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved configuration URLs
          schema:
            $ref: '#/definitions/internal_controllers.DeviceConfigResponse'
        "400":
          description: incorrect eth addr format
        "404":
          description: Not Found - No templates available for the given parameters
      tags:
      - vehicle-signal-decoding
  /device-config/eth-addr/{ethAddr}/jobs/pending:
    get:
      description: Retrieve the jobs based on device's Ethereum Address.
      parameters:
      - description: Ethereum Address
        in: path
        name: ethAddr
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved jobs
          schema:
            $ref: '#/definitions/internal_controllers.JobResponse'
        "400":
          description: incorrect eth addr format
      tags:
      - vehicle-signal-decoding
  /device-config/eth-addr/{ethAddr}/urls:
    get:
      description: Retrieve the URLs for PID, DeviceSettings, and DBC configuration
        based on device's Ethereum Address. These could be empty if not configs available
      parameters:
      - description: Ethereum Address
        in: path
        name: ethAddr
        required: true
        type: string
      - description: CAN Protocol, '6' or '7'
        in: query
        name: protocol
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved configuration URLs
          schema:
            $ref: '#/definitions/internal_controllers.DeviceConfigResponse'
        "400":
          description: incorrect eth addr format
        "404":
          description: Not Found - No templates available for the given parameters
      tags:
      - vehicle-signal-decoding
  /device-config/settings/{name}:
    get:
      description: |-
        Fetches the device settings configurations from device_settings table given a name. Note that device settings mostly only vary by powertrain and
        may or may not be attached to a specific template. To return protobuf: "application/x-protobuf"
        Note that the templateName returned here is actually the device setting name
      parameters:
      - description: name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved Device Settings
          schema:
            $ref: '#/definitions/github_com_DIMO-Network_vehicle-signal-decoding_pkg_grpc.DeviceSetting'
        "404":
          description: No Device Settings data found for the given name.
      tags:
      - vehicle-signal-decoding
  /device-config/vin/{vin}/urls:
    get:
      description: Retrieve the URLs for PID, DeviceSettings, and DBC configuration
        based on a given VIN. These could be empty if not configs available
      parameters:
      - description: vehicle identification number (VIN)
        in: path
        name: vin
        required: true
        type: string
      - description: CAN Protocol, '6' or '7'
        in: query
        name: protocol
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved configuration URLs
          schema:
            $ref: '#/definitions/internal_controllers.DeviceConfigResponse'
        "404":
          description: Not Found - No templates available for the given parameters
      tags:
      - vehicle-signal-decoding
swagger: "2.0"
