name: buildpushdev
on:
  push:
    branches:
      - main
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_test:
    # The type of runner that the job will run on
    name: buildpushdev
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Get short SHA
        id: slug
        run: echo "BUILD_TAG=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_OUTPUT

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: false
        
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./resources/docker/Dockerfile
          push: true
          tags: dimozone/vehicle-signal-decoding:${{ steps.slug.outputs.BUILD_TAG }}, dimozone/vehicle-signal-decoding:latest

      - name: Update Image Version in the related HelmChart values.yaml
        uses: fjogeleit/yaml-update-action@v1
        with:
          valueFile: 'charts/vehicle-signal-decoding/values.yaml'
          propertyPath: 'image.tag'
          value: ${{ steps.slug.outputs.BUILD_TAG }}
          branch: main
          message: 'Update Image Version to ${{ steps.slug.outputs.BUILD_TAG }}'
